[package]
name = "fake_log"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
fake = "2.4"
rand = "0.8.5"
clap = { version = "3.1.18", features = ["derive"] }
